name: CodeQuality
on:
  workflow_dispatch:
    inputs:
      explicit_checks:
        type: string
  repository_dispatch:
  push:
    branches:
      - '**'
      - '!main'
      - '!feature'
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
      - '!.github/workflows/CodeQuality.yml'

  pull_request:
    types: [opened, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
      - '!.github/workflows/lcov_exclude'
      - '!.github/workflows/CodeQuality.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-20.04

    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install
        shell: bash
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build clang-format-11 && sudo pip3 install cmake-format black cxxheaderparser pcpp

      - name: List Installed Packages
        shell: bash
        run: pip3 freeze

      - name: Format Check
        shell: bash
        run: |
          clang-format --version
          clang-format --dump-config
          black --version
          make format-check-silent

