name: Local Nessie Testing
on: [push, pull_request,repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

env:
  BASE_BRANCH: ${{ github.base_ref || (endsWith(github.ref, '_feature') && 'feature' || 'main') }}

jobs:
  rest:
    name: Test against Nessie Catalog
    runs-on: ubuntu-latest
    env:
      VCPKG_TARGET_TRIPLET: 'x64-linux-release'
      GEN: ninja
      VCPKG_FEATURE_FLAGS: "-binarycaching"
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      PIP_BREAK_SYSTEM_PACKAGES: 1

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: ce613c41372b23b1f51333815feb3edd87ef8a8b

      - name: Install nessie required packages
        shell: bash
        run: |
          # install docker
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          # install java
          sudo apt install -y -qq openjdk-21-jre-headless
          sudo apt install -y -qq openjdk-21-jdk-headless
          sudo apt-get install -y -qq python3-venv
          git clone https://github.com/projectnessie/nessie.git nessie

      - name: Install Ninja
        shell: bash
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}
          save: ${{ github.ref == 'refs/heads/main' || github.repository != 'duckdb/duckdb' }}

      - name: Start Nessie
        working-directory: nessie/docker
        run: |
          sed -i '/healthcheck/,/]/ s/\$/$$/g' catalog-auth-s3/docker-compose.yml
          docker-compose -f catalog-auth-s3/docker-compose.yml up -d

      - name: Build extension
        env:
          GEN: ninja
          STATIC_LIBCPP: 1
        run: |
          make release

      - name: Wait for Nessie/Keycloak
        run: |
          max_attempts=30
          attempt=1
          while ! curl -sf "http://localhost:8080/realms/master/.well-known/openid-configuration"; do
            if [ $attempt -gt $max_attempts ]; then
              echo "Keycloak failed to initialize after $max_attempts attempts"
              exit 1
            fi
            echo "Waiting for Keycloak to initialize (attempt $attempt/$max_attempts)..."
            sleep 5
            attempt=$((attempt + 1))
          done
          echo "Keycloak is healthy"

      - name: Test with rest catalog
        env:
          NESSIE_SERVER_AVAILABLE: 1
        run: |
          ./build/release/test/unittest "$PWD/test/*" --list-test-names-only || true
          ./build/release/test/unittest "$PWD/test/*"

